# Generated by Django 6.0.4 on 2026-05-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_ujap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioujap',
            name='password',
        ),
    ]
