# Generated by Django 6.0.4 on 2026-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ujap', '0002_remove_usuarioujap_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='horarios_personales',
            field=models.ManyToManyField(blank=True, related_name='estudiantes_inscritos', to='web_ujap.horario', verbose_name='Horarios personales'),
        ),
    ]
